name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
           docker build . --tag ghcr.io/classicube/minimal-psn00b:latest
           docker run ghcr.io/classicube/minimal-psn00b:latest
           docker push ghcr.io/classicube/minimal-psn00b:latest

